### PR TITLE
Hackathon2021 cflag probes

### PR DESCRIPTION
**Pull request by mathrack**

### CODE REVIEW

**Comment by mathrack** [comment]
This branch is not ready to merge yet.

**Comment by mathrack** [comment]
Fix needed:

1. the probes should not rely on a dedicated prm file

Potential fix needed:

2. the monitoring of gradients is blended inside the transport subroutines

**Comment by mathrack** [comment]
Regarding the fix needed, I suggest to add 2 namelists in the i3d file :

- one namelist will contain the probes setup : number of probes, and potentially the flags to monitor gradients & print all digits.
- the other namelist will contain the position of the probes

**Comment by pbartholomew08** [comment]
I think we do something similar at another point (for ibm perhaps?)
In the main namelist you flag something is happening, this may cause some allocations, the next namelist then works based on what it already knows about what is coming

**Comment by mathrack** [comment]
@pbartholomew08 sounds fine. I will add a trigger for one unified probe namelist inside the `InOutParam` namelist

**Comment by pbartholomew08** [comment]
👍 Pull Request incoming to try and resolve blending functionality

**Comment by mathrack** [comment]
The branch seems ready for merging. Potential upgrade could be to tune the frequency for output at the probes. Currently each time step is written.

**Review by pbartholomew08 — APPROVED** [review]

**Pull request merged**
